[package]
name = "cauchy"
version = "0.2.2"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

description = "Trait for real and complex numbers"
documentation = "https://docs.rs/cauchy"
repository = "https://github.com/termoshtt/cauchy"
keywords = []
categories = ["algorithms"]
license = "MIT"

[dependencies]
num-traits = "0.2"
serde = "1"
rand = "0.7"

[dependencies.num-complex]
version = "0.2.1"
features = ["serde", "rand"]
